name: Lint Python API

on:
  push:
    branches: [ main ]

jobs:
  lint-python:
    name: Lint Python API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd api
          pip install flake8

      - name: Lint Python API
        run: |
          cd api
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: lint-results.txt

      - name: Comment on PR if there's an error
        if: contains(github.workspace/lint-results.txt, 'error')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: github.context.pullRequest.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: 'Linting failed! Please check the lint results.'
            })