name: Lint Angular App

on:
  push:
    branches: [ main ]

jobs:
  lint-js:
    name: Lint Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd app
          npm install

      - name: Lint Angular app
        run: |
          cd app
          ng lint

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: lint-results.txt

      - name: Comment on PR if there's an error
        if: contains(github.workspace/lint-results.txt, 'error')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: github.context.pullRequest.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: 'Linting failed! Please check the lint results.'
            })