name: Python Tester

# On PR to main or nonprod
on:
  pull_request:
    branches:
      - main
      - nonprod

jobs:
  python-test:
    name: Test the Python API
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run tests within the API container
    - name: Run tests within the API container
      run: |
        docker compose up -d
        docker exec -i backend-container python test.py <<< "y" > python-test-results.txt
        docker cp backend-container:/api/python-test-results.txt python-test-results.txt

    # Upload test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: python-test-results
        path: python-test-results.txt

  validate-tests:
    name: Validate test results
    runs-on: ubuntu-latest
    needs: python-test

    steps:
    - uses: actions/checkout@v4

    # Download test results artifact
    - name: Download test results
      uses: actions/download-artifact@v3
      with:
        name: python-test-results
        path: .

    - name: Comment on PR if there's an error
      if: "!contains(steps.download.outputs['python-test-results'], 'OK')"
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const testResults = fs.readFileSync('python-test-results.txt', 'utf8');
          github.issues.createComment({
            issue_number: github.context.payload.pull_request.number,
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            body: 'Testing failed! Please check the test results below:\n\n```${testResults}```'
          });
