name: Python Tester

# On PR to main or nonprod
on:
  pull_request:
    branches:
      - main
      - nonprod

jobs:
  python-test:
    name: Test the Python API
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run the app's containers
      run: |
        docker compose up -d
    
    - name: Get the IP address of the postgres container
      run: |
        POSTGRES_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres)
        echo "POSTGRES_IP=$POSTGRES_IP" >> $GITHUB_ENV

    - name: Test the Python API
      env:
        POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_IP}:5432/${POSTGRES_DB}
      run: |
        docker exec -i backend-container python test.py <<< "y"