name: Angular Linter

on:
  pull_request:
    branches:
      - main
      - nonprod

jobs:
  lint-js:
    name: Lint the Angular App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd app
        npm install
        npm install -g @angular/cli@17 > /dev/null 
        ng add @angular-eslint/schematics --skip-confirmation

    - name: Lint Angular app
      run: |
        cd app
        ng lint