name: Angular Tester

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-js:
    name: Test the Angular App

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd app
    - run: npm ci
    # - run: npm install -g @angular/cli@17
    - run: npm run build --prod
    - run: npm test