name: Angular Linter

on:
  pull_request:
    branches:
      - main
      - nonprod

jobs:
  lint-js:
    name: Lint the Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore cached dependencies 
        id: cache-restore 
        uses: actions/cache@v3 
        with: 
          path: ./app/node_modules 
          key: npm-${{ hashFiles('./app/package-lock.json') }} 
        
      - name: Install dependencies 
        if: steps.cache-restore.outputs.cache-hit != 'true' 
        run: | 
          cd app 
          npm ci - ignore-scripts 
        
      - name: Lint 
        run: | 
          cd app 
          npm run lint


      # - name: Install dependencies
      #   run: |
      #     cd app
      #     npm install
      #     npm install -g @angular/cli@17 > /dev/null 
      #     ng add @angular-eslint/schematics

      # - name: Lint Angular app
      #   run: |
      #     cd app
      #     ng lint