name: Python Tester

# On PR to main or nonprod
on:
  pull_request:
    branches:
      - main
      - nonprod

jobs:
  python-test:
    name: Test the Python API
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Run tests within the API container
    - name: Run tests within the API container
      run: |
        docker compose up -d
        docker compose exec backend-container python test.py <<< "y"